apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: workshop-quarkus-hello_bycountry
  title: Hello Quarkus
  description: |
    Introduction to Red Hat Dev Spaces with a Quarkus translation service
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - devspaces
    - quarkus
# links:
#    - url: https://<openshift-cluster>/#<hosted-git-repo>
#      title: "Launch from Dev Spaces"
#      icon: web
spec:
  type: module
  lifecycle: production
  owner: group:default/workshop-admins
  subcomponentOf: component:default/workshop-repository
